version: "3.7"
services:
  soft-ib-users:
    image: soft-ib-users:1.0
    ports:
      - 8085:8081
    depends_on:
      - mysql_db_soft-ib_users
  mysql_db_soft-ib_users:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: softibusers
      MYSQL_ROOT_PASSWORD: root
      