version: "3.7"
services:
  eureka:
    image: eureka:1.0
    ports:
      - 8761:8761
  zuul:
    image: zuul:1.0
    ports:
      - 8862:8862
    depends_on:
      - eureka
  soft-ib-core:
    image: soft-ib-core:1.0
    ports:
      - 8085:8081
    depends_on:
      db_core:
        condition: service_healthy
  soft-ib-help-center:
    image: soft-ib-help-center:1.0
    ports:
      - 8086:8083
    depends_on:
      db_helpCenter:
        condition: service_healthy
  soft-ib-account-manager:
    image: soft-ib-account-manager:1.0
    ports:
      - 8086:8083
    depends_on:
      db_accountManager:
        condition: service_healthy
  db_core:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: core
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  db_helpCenter :
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: accountManager
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  db_accountManager :
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: accountManager
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
